GET http://localhost:3001/api/brewery

###
GET http://localhost:3001/api/brewery/6325ea5dab6d56149cc52923

###
POST http://localhost:3001/api/brewery
Content-Type: application/json

    {
        "name": "Flying Bike",
        "location": "Seattle",
        "userId": "6343b17ce371cddea3ca8bb7"
    }

###
PUT http://localhost:3001/api/brewery/6325ea64ab6d56149cc52925
Content-Type: application/json

    {
        "tasted": false
    }

###
DELETE http://localhost:3001/api/brewery/633d65974114bc52375717d3