GET http://localhost:3001/api/brewery

###
GET http://localhost:3001/api/brewery/6325ea5dab6d56149cc52923

###
POST http://localhost:3001/api/brewery
Content-Type: application/json

    {
        "name": "Urban Family",
        "location": "Seattle"
    }

###
PUT http://localhost:3001/api/brewery/6325ea64ab6d56149cc52925
Content-Type: application/json

    {
        "tasted": false
    }

###
DELETE http://localhost:3001/api/brewery/632d4d1346d7c805ff7c64f3