GET http://localhost:3001/api/brewery

###
GET http://localhost:3001/api/brewery/6325ea0fab6d56149cc5291d

###
POST http://localhost:3001/api/brewery
Content-Type: application/json

    {
        "name": "Postdoc",
        "location": "Redmond",
        "tasted": true
    }

###
PUT http://localhost:3001/api/brewery/632d4d1346d7c805ff7c64f3
Content-Type: application/json

    {
        "tasted": false
    }

###
DELETE http://localhost:3001/api/brewery/632d4d1346d7c805ff7c64f3