GET http://localhost:3001/api/users/

###

POST http://localhost:3001/api/users/registration
Content-Type: application/json

    {
        "username": "new_user",
        "email": "newuser@email.com",
        "password": "1234"
    }

###

POST http://localhost:3001/api/users/login 
Content-Type: application/json

{
    "username": "new_user",
    "password": "1234"
}